<?php $s = array(3) {
     [0]=> array(6) { 
        ["id"]      => string(1) "2" 
        ["user_id"] => string(1) "1" 
        ["group_id"]=> string(1) "2" 
        ["username"]=> string(13) "administrator" 
        ["email"]   => string(15) "admin@admin.com" 
        ["name"]    => string(7) "members" } 
     [1]=> array(6) { 
        ["id"]      => string(1) "1" 
        ["user_id"] => string(1) "1" 
        ["group_id"]=> string(1) "1" 
        ["username"]=> string(13) "administrator" 
        ["email"]   => string(15) "admin@admin.com" 
        ["name"]    => string(5) "admin" } 
     [2]=> array(6) { 
        ["id"]      => string(1) "3" 
        ["user_id"] => string(1) "2" 
        ["group_id"]=> string(1) "2" 
        ["username"]=> string(6) "member" 
        ["email"]   => string(21) "david.robby@ymail.com" 
        ["name"]    => string(7) "members" } } ?>